# Generated by Django 5.2.7 on 2026-05-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_CRUD", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentDetails",
            new_name="StudentDetail",
        ),
    ]
