# Generated by Django 6.0.5 on 2026-05-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
