# Generated by Django 6.0.5 on 2026-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=50, unique=True)),
                ('student_course', models.CharField(max_length=75)),
                ('student_enrollement', models.DateField()),
            ],
        ),
    ]
