# Generated by Django 6.0.5 on 2026-05-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_CRUD', '0002_rename_studentdetails_studentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='student_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='student_enrollement',
            new_name='enrollment_date',
        ),
    ]
